---
name: Fey-ORM
version: 0.17
author:
  - 'Dave Rolsky, <autarch@urth.org>'
abstract: A Fey-based ORM
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Devel::GlobalDestruction: 0
  Exception::Class: 0
  Exporter: 0
  Fey: 0.15
  Fey::DBIManager: 0.07
  List::MoreUtils: 0
  Moose: 0.63
  MooseX::AttributeHelpers: 0.13
  MooseX::ClassAttribute: 0
  MooseX::StrictConstructor: 0.07
  Scalar::Util: 0
build_requires:
  Fey::Test: 0.05
  Test::Exception: 0
  Test::More: 0
provides:
  Fey::Hash::ColumnsKey:
    file: lib/Fey/Hash/ColumnsKey.pm
  Fey::Meta::Attribute::FromSelect:
    file: lib/Fey/Meta/Attribute/FromSelect.pm
  Fey::Meta::Class::Schema:
    file: lib/Fey/Meta/Class/Schema.pm
  Fey::Meta::Class::Table:
    file: lib/Fey/Meta/Class/Table.pm
  Fey::Meta::FK:
    file: lib/Fey/Meta/FK.pm
  Fey::Meta::HasMany:
    file: lib/Fey/Meta/HasMany.pm
  Fey::Meta::HasMany::ViaFK:
    file: lib/Fey/Meta/HasMany/ViaFK.pm
  Fey::Meta::HasMany::ViaSelect:
    file: lib/Fey/Meta/HasMany/ViaSelect.pm
  Fey::Meta::HasOne:
    file: lib/Fey/Meta/HasOne.pm
  Fey::Meta::HasOne::ViaFK:
    file: lib/Fey/Meta/HasOne/ViaFK.pm
  Fey::Meta::HasOne::ViaSelect:
    file: lib/Fey/Meta/HasOne/ViaSelect.pm
  Fey::Meta::Method::Constructor:
    file: lib/Fey/Meta/Method/Constructor.pm
  Fey::ORM:
    file: lib/Fey/ORM.pm
    version: 0.17
  Fey::ORM::Exceptions:
    file: lib/Fey/ORM/Exceptions.pm
  Fey::ORM::Schema:
    file: lib/Fey/ORM/Schema.pm
  Fey::ORM::Table:
    file: lib/Fey/ORM/Table.pm
  Fey::Object::Iterator:
    file: lib/Fey/Object/Iterator.pm
  Fey::Object::Iterator::Caching:
    file: lib/Fey/Object/Iterator/Caching.pm
  Fey::Object::Schema:
    file: lib/Fey/Object/Schema.pm
  Fey::Object::Table:
    file: lib/Fey/Object/Table.pm
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
