---
abstract: 'A Fey-based ORM (If you like SQL, you might like Fey::ORM)'
author:
  - 'Dave Rolsky <autarch@urth.org>'
build_requires:
  Exporter: 0
  Fey::FakeDBI: 0
  Fey::Literal::String: 0
  Fey::Test: 0.05
  Test::Fatal: 0
  Test::More: 0.88
  lib: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300039, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Fey-ORM
requires:
  Class::Load: 0
  Class::MOP::Method::Generated: 0
  Devel::GlobalDestruction: 0
  Exception::Class: 0
  Fey: 0.39
  Fey::DBIManager: 0.07
  Fey::Exceptions: 0
  Fey::Literal::Function: 0
  Fey::Placeholder: 0
  Fey::SQL: 0
  Fey::Table: 0
  List::AllUtils: 0
  List::Util: 0
  Moose: 1.15
  Moose::Exporter: 0
  Moose::Meta::Attribute: 0
  Moose::Meta::Class: 0
  Moose::Meta::Method: 0
  Moose::Meta::Method::Constructor: 0
  Moose::Role: 0
  Moose::Util::MetaRole: 0
  Moose::Util::TypeConstraints: 0
  MooseX::ClassAttribute: 0.24
  MooseX::Params::Validate: 0
  MooseX::SemiAffordanceAccessor: 0
  MooseX::StrictConstructor: 0.13
  MooseX::Types: 0
  MooseX::Types::Combine: 0
  MooseX::Types::Moose: 0
  Object::ID: 0
  Scalar::Util: 0
  Sub::Exporter: 0
  Try::Tiny: 0
  base: 0
  namespace::autoclean: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Fey-ORM
  repository: git://git.urth.org/Fey-ORM.git
version: 0.46
