---
name: Fey-ORM
version: 0.28
author:
  - 'Dave Rolsky, <autarch@urth.org>'
abstract: A Fey-based ORM
license: perl
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Fey-ORM
  homepage: http://www.fey-project.org/
  license: http://dev.perl.org/licenses/
  repository: http://hg.urth.org/hg/Fey-ORM
build_requires:
  Fey::Test: 0.05
  Test::Exception: 0
  Test::More: 0
requires:
  Devel::GlobalDestruction: 0
  Exception::Class: 0
  Fey: 0.15
  Fey::DBIManager: 0.07
  List::MoreUtils: 0
  Moose: 0.90
  MooseX::ClassAttribute: 0.08
  MooseX::SemiAffordanceAccessor: 0
  MooseX::StrictConstructor: 0.08
  Scalar::Util: 0
  Sub::Exporter: 0
configure_requires:
  Module::Build: 0.35
provides:
  Fey::Hash::ColumnsKey:
    file: lib/Fey/Hash/ColumnsKey.pm
    version: 0.28
  Fey::Meta::Attribute::FromColumn:
    file: lib/Fey/Meta/Attribute/FromColumn.pm
    version: 0.28
  Fey::Meta::Attribute::FromInflator:
    file: lib/Fey/Meta/Attribute/FromInflator.pm
    version: 0.28
  Fey::Meta::Attribute::FromSelect:
    file: lib/Fey/Meta/Attribute/FromSelect.pm
    version: 0.28
  Fey::Meta::Class::Schema:
    file: lib/Fey/Meta/Class/Schema.pm
    version: 0.28
  Fey::Meta::Class::Table:
    file: lib/Fey/Meta/Class/Table.pm
    version: 0.28
  Fey::Meta::FK:
    file: lib/Fey/Meta/FK.pm
    version: 0.28
  Fey::Meta::HasMany:
    file: lib/Fey/Meta/HasMany.pm
    version: 0.28
  Fey::Meta::HasMany::ViaFK:
    file: lib/Fey/Meta/HasMany/ViaFK.pm
    version: 0.28
  Fey::Meta::HasMany::ViaSelect:
    file: lib/Fey/Meta/HasMany/ViaSelect.pm
    version: 0.28
  Fey::Meta::HasOne:
    file: lib/Fey/Meta/HasOne.pm
    version: 0.28
  Fey::Meta::HasOne::ViaFK:
    file: lib/Fey/Meta/HasOne/ViaFK.pm
    version: 0.28
  Fey::Meta::HasOne::ViaSelect:
    file: lib/Fey/Meta/HasOne/ViaSelect.pm
    version: 0.28
  Fey::Meta::Method::Constructor:
    file: lib/Fey/Meta/Method/Constructor.pm
    version: 0.28
  Fey::ORM:
    file: lib/Fey/ORM.pm
    version: 0.28
  Fey::ORM::Exceptions:
    file: lib/Fey/ORM/Exceptions.pm
    version: 0.28
  Fey::ORM::Policy:
    file: lib/Fey/ORM/Policy.pm
    version: 0.28
  Fey::ORM::Role::Iterator:
    file: lib/Fey/ORM/Role/Iterator.pm
    version: 0.28
  Fey::ORM::Schema:
    file: lib/Fey/ORM/Schema.pm
    version: 0.28
  Fey::ORM::Table:
    file: lib/Fey/ORM/Table.pm
    version: 0.28
  Fey::Object::Iterator::FromArray:
    file: lib/Fey/Object/Iterator/FromArray.pm
    version: 0.28
  Fey::Object::Iterator::FromSelect:
    file: lib/Fey/Object/Iterator/FromSelect.pm
    version: 0.28
  Fey::Object::Iterator::FromSelect::Caching:
    file: lib/Fey/Object/Iterator/FromSelect/Caching.pm
    version: 0.28
  Fey::Object::Policy:
    file: lib/Fey/Object/Policy.pm
    version: 0.28
  Fey::Object::Schema:
    file: lib/Fey/Object/Schema.pm
    version: 0.28
  Fey::Object::Table:
    file: lib/Fey/Object/Table.pm
    version: 0.28
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
