---
abstract: 'A Fey-based ORM (If you like SQL, you might like Fey::ORM)'
author:
  - 'Dave Rolsky <autarch@urth.org>'
build_requires:
  Fey::Test: 0.05
  Test::Exception: 0
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200004, CPAN::Meta::Converter version 2.110240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Fey-ORM
requires:
  Devel::GlobalDestruction: 0
  Exception::Class: 0
  Fey: 0.39
  Fey::DBIManager: 0.07
  List::AllUtils: 0
  Moose: 1.15
  MooseX::ClassAttribute: 0.17
  MooseX::SemiAffordanceAccessor: 0
  MooseX::StrictConstructor: 0.08
  MooseX::Types: 0
  Object::ID: 0
  Scalar::Util: 0
  Sub::Exporter: 0
  namespace::autoclean: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Fey-ORM
  repository: http://hg.urth.org/hg/Fey-ORM
version: 0.41
